
import Head from 'next/head'

import { ImgTitleText } from '@/Components/ImgTitleText'
import { HeaderFiltro } from '@/Components/HeaderFiltro'
import { ContentFiltros } from '@/Components/ContentFiltros'
import { Footer } from '@/Components/Footer'
import { InputSearch } from '@/Components/InputSearch'
import { LogoIcons } from '@/Components/LogoIcons'
import { MenuTags } from '@/Components/MenuTags'
import { MenuFiltro } from '@/Components/MenuFiltro'
import { SubMenu } from '@/Components/SubMenu'
import { Container } from '@/Components/Container'
import { Text } from '@/Components/Text'
import { Title } from '@/Components/Title'

export default function Home() {
  return (
    <>
      <Head>
        <title>TripAdvisor </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LogoIcons />
      <MenuTags />
      <Container>
        <MenuFiltro />
        <Title >Tours de naturaleza y vida silvestre en Cúcuta</Title>
        <HeaderFiltro />


        <ContentFiltros
        />

       
      </Container>

      <Footer

      />





    </>
  )
}
